# Generated by Django 3.2.5 on 2022-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorium', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='territorium/fotos/default.png', upload_to='territorium/fotos'),
        ),
    ]
